name: Build APK Test
on: workflow_dispatch

jobs:
  build-android:
    name: Build in Docker (Ubuntu 20.04)
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
      - name: Install dependencies
        run: |
          apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
            git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev \
            libssl-dev automake openjdk-17-jdk curl wget lsb-release software-properties-common

      - name: Install Buildozer
        run: |
          pip3 install --upgrade --user Cython virtualenv buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH:$HOME/.local/bin
          buildozer -v android debug

      - name: Rename APK
        run: mv bin/*.apk bin/test.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: test-apk
          path: bin/test.apk
