name: Build APK Test
on: workflow_dispatch
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest  # Now points to 22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev \
            libssl-dev automake openjdk-17-jdk

      - name: Install Buildozer and Python tools
        run: |
          python3 -m pip install --user --upgrade Cython virtualenv buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          buildozer -v android debug

      - name: Rename APK
        run: mv bin/*.apk bin/test.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: test-apk
          path: bin/test.apk
