name: Build
on:
  push:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Python and upgrade dependencies
      - name: Set up Python and upgrade dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version here

      - name: Upgrade setuptools and cython
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools cython

      # Install Java (required for Buildozer)
      - name: Install Java 8
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk

      # Install Android dependencies (SDK & NDK)
      - name: Install Android dependencies
        run: |
          sudo apt-get install -y unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android
          yes | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android --licenses
          $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android "platform-tools" "build-tools;29.0.2" "android-29" "ndk-bundle"

      # Build with Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
