name: Build Kivy APK

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust Python version if needed

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Buildozer
        run: |
          pip install buildozer  # Install latest stable Buildozer

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Ensure your dependencies are installed (if needed)

      - name: Build APK
        run: |
          buildozer -v android debug  # Run Buildozer command to build APK
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk  # Upload APK file generated by Buildozer
